version: '3.7'
services:
  redis:
    image: redis
    restart: always
    networks: 
      - webnet
  db:
    image: postgres
    restart: always
    networks: 
      - webnet
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  server:
    build: '.'
    restart: always
    networks: 
      - webnet
    depends_on:
      - db
    env_file:
      - '.env'
    ports:
      - '4000:4000'
    volumes:
      - '.:/usr/app'
    command: yarn dev
networks:
  webnet: