module.exports = [
  {
    name: 'production',
    type: 'postgres',
    host: process.env.POSTGRES_HOST,
    port: 5432,
    database: process.env.POSTGRES_DB,
    username: process.env.POSTGRES_USER,
    password: process.env.POSTGRES_PASSWORD,
    logging: false,
    dropSchema: false,
    synchronize: false,
    entities: ['src/entity/**/*'],
    migrations: ['src/migration/**/*'],
    subscribers: ['src/subscriber/**/*'],
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
  {
    name: 'development',
    type: 'postgres',
    host: process.env.POSTGRES_HOST,
    port: 5432,
    database: process.env.POSTGRES_DB,
    username: process.env.POSTGRES_USER,
    password: process.env.POSTGRES_PASSWORD,
    logging: true,
    dropSchema: true,
    synchronize: true,
    entities: ['src/entity/**/*'],
    migrations: ['src/migration/**/*'],
    subscribers: ['src/subscriber/**/*'],
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
];
